### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by webalexeu** [filipvh/hass-nhc2#1]
Hello,

The plugin doens't connect to NHC2

Disconnected
14:04 /usr/local/lib/python3.7/site-packages/nhc2_coco/coco.py (WARNING) - message first occured at 14:02 and shows up 2 times

Thank you for your support,
Alex

**Comment by filipvh** [comment]
it should but i'm not sure if I pushed my last version

**Comment by webalexeu** [comment]
Ok. How can I check if I have the last version?

**Comment by filipvh** [comment]
I'll look into pushing the latest version tonight

**Comment by filipvh** [comment]
The latest version should be on master now.

**Comment by webalexeu** [comment]
Still the same issue
2019-07-25 09:39:26 WARNING (Thread-2) [nhc2_coco.coco] Disconnected

Maybe it's something else?

**Comment by filipvh** [comment]
How did you add my component and how did you do your config?

**Comment by webalexeu** [comment]
I add all sources inside a folder called nhc2 under custom_components
And config is inside configuration.yaml

**Comment by filipvh** [comment]
Can you show me your config? Without password :)

**Comment by webalexeu** [comment]
nhc2:
  host: x.x.x.x
  port: 8883
  username: "xxxxxxxxxxxxxxxxxxxxxxxx"
  password: !secret nhc2_password

**Comment by filipvh** [comment]
Is the IP between quotes? don't know if it matters, but my config now is:
nhc2:
  host: '123.123.123.1'
  port: 8883
  username: '12345678-1234-1234-1234-123456789012'
  password: 'mypassword'

yeah i should move that password to my secrets file, but this works at home, months at end
have setup with the IP of NHC2 to the same (dhcp-config)

**Comment by filipvh** [comment]
btw, not my real passwd ;)

**Comment by webalexeu** [comment]
nhc2:
  host: 'x.x.x.x'
  port: 8883
  username: 'xxxxxxxxxx'
  password: 'xxxxxxxxxx'

Did like you but still not working

**Comment by filipvh** [comment]
Try to enable debug logging for custom_components
![image](https://user-images.githubusercontent.com/6095002/61952581-86ad7700-afb4-11e9-9a1a-88db98e0f4ff.png)

**Comment by webalexeu** [comment]
2019-07-26 15:02:12 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for nhc2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-07-26 15:02:14 DEBUG (MainThread) [custom_components.nhc2] Connecting to 10.0.0.100:8883
2019-07-26 15:02:14 WARNING (Thread-2) [nhc2_coco.coco] Disconnected

For your info, I'm using ha on docker

**Comment by filipvh** [comment]
Is it possible, that from the container where it is running, it cannot acces the local network? 
You could download a MQTT client (eg. MQTT.fx) use your ip, username, password and certificate can be found: https://raw.githubusercontent.com/filipvh/nhc2-coco/master/nhc2_coco/coco_ca.pem
Then subscribe to the subject # en see if you get some messages.
If you can connect from your local PC, but not hass, it might be a networking issue.

**Comment by webalexeu** [comment]
The docker host has access to NHC because I've openhab install on the host and it's connected to NHC
From the container, I can ping NHC. I need to test from the container a mqtt connection to confirm but normally, network connectivity should be fine

**Comment by filipvh** [comment]
it's NHC2 you have right? 
![image](https://user-images.githubusercontent.com/6095002/61954714-bad76680-afb9-11e9-8c27-3b4997890aec.png)

**Comment by webalexeu** [comment]
Yes yes. Openhab with MQTT connection to NHC2 works ;-)

**Comment by webalexeu** [comment]
When I try with default mqtt from HA
 [homeassistant.components.mqtt] Failed to connect due to exception: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '10.0.0.100'. (_ssl.c:1076)
I'm using the PEM cert file you provide (coco_ca.pem)

**Comment by webalexeu** [comment]
If it's an SSL issue, it will be logged?

**Comment by steven1313** [comment]
I'm having the same response in the log 'WARNING (Thread-2) [nhc2_coco.coco] Disconnected'. Using the Niko wireless smart hub with NHC2.
Did the problem discussed here get a solution?

**Comment by filipvh** [comment]
It's hard for me to get a grasp on what's going wrong. And I don't have much time to spend on this :(

**Comment by filipvh** [comment]
@webalexeu  and @steven1313  any updates? I'm going to try to get back at this, maybe next month.

**Comment by steven1313** [comment]
No, still the same situation... If i can help in any way or provide extra
information, please let me know!

Op za 11 jan. 2020 om 23:17 schreef Filip Van Ham <notifications@github.com

**Comment by FlenzZ** [comment]
I have exactly the same problem. Anyone already succeeded in solving the issue?

**Comment by filipvh** [comment]
@steven1313 @FlenzZ @webalexeu 
If one of you would like, we could look at you specific issues one of the coming days.
https://join.slack.com/t/newworkspace-xgi8370/shared_invite/zt-j6qy16sl-kZF6V__uTCLVLpZUNutJWA

**Comment by filipvh** [comment]
resolved in chat.
**latest version solves a lot of issues**

- remove integration from configuration.yaml
- remove integration from gui (Configuration > Integrations)
- restart hass
- OPTION 1 go to Configuration > Integrations, add new one (search for Niko ...)
- OPTION 2 remove custom component from custom components dir and user HACS (working on that this weekend)

**Comment by FlenzZ** [comment]
Thanks! Works perfectly!

**Comment by 86hakan** [comment]
I have the same problem 
Disconnected
10:54:01 – /usr/local/lib/python3.8/site-packages/nhc2_coco/coco.py (WARNING)

every time after i restart the system.
and when im trying to do the solutions above i manual write the ip-adress to niko but then i see the status but cannot change anyting to niko
